query productsListLoad {
  products {
    ...ProductsListProduct
  }
}

mutation productRemove($id: String!) {
  result: productRemove(id: $id)
}

subscription test {
  product: productAdded {
    ...ProductsListProduct
  }
}

fragment ProductsListProduct on ProductNode {
  id
  image
  category
  name
  price
  description
}
